### ISSUE TITLE
Datepickers aren't working on "Add an Event" (do work on Edit)

### ISSUE THREAD

**Issue by akf** [pdxactivist/pdxactivist#14]
http://pdxactivist.org/events/new

Datepickers don't pop up when you edit the date fields. They do show up on the Edit Event form. 

I don't see any javascript errors until I've entered a date and tabbed to the next field. I'm attaching a screenshot of two errors -- the first appears after I enter a date and the second after I enter a time. 

I will admit to using an outdated version of Chrome today: Version 49.0.2623.110 (64-bit)
I'm running an Ubuntu LTS release and Google decided to nope out a little early. 
![pdxactivist-errs](https://cloud.githubusercontent.com/assets/35591/22859859/03d2414c-f0a0-11e6-8368-31a5900b7bca.png)

**Comment by jhelwig** [comment]
Interesting. When I go there with on OS X 10.11.6, I don't get any JS errors, and the "When" date/time pickers appear to work on the new event page.

Browsers checked:
* Chrome 56.0.2924.87 (64-bit)
* Firefox 50.1.0
* Firefox 51.0.1 (64-bit)
* Firefox Developer Edition 52.0a2 (2017-01-16) (64-bit)
* Firefox Developer Edition 53.0a2 (2017-02-11) (64-bit)
* Safari 10.0.3 (11602.4.8.0.1)

Should definitely look to see what's different between the new event page, and the edit event page with the date pickers. Does this also happen for you on the main Calagator site? I have a feeling this is a bug in Calagator, since I'm not sure what would cause this to be PDX Activist specific.

**Comment by akf** [comment]
Good news! The datepickers work for me on calagator.org, and on pdxactivist.org, after I did a hard reload on the latter. (Weirdly, I have to do this every time I visit the page, but that clearly points to a cache issue on my end.) Something must have loaded incompletely on my first visit. 

The error messages I was seeing seem to be triggered by putting something "wrong" into a date or time field. 

So, nevermind. Sorry I didn't check this before reporting.

**Comment by jhelwig** [comment]
No worries!
