### ISSUE TITLE
accented characters

### ISSUE THREAD

**Issue by ghost** [pdxactivist/pdxactivist#17]
Hi y'all, did you miss me?
So there's an event with 2 FB event profiles - one in English, one in Spanish. The Spanish one borks, the English one slurped up beautifully. https://pdxactivist.org/events/513  So Miss Bright Spot that I am, I thought I'd combine them. And here's a shocker - I get the "there's been a problem screen" after adding the Spanish.

Please tell me that the two spanish accents are within ASCII Latin, please? I'm going to fool around with this on the re-typing end...

**Comment by ghost** [comment]
Okay. I just cut and paste into the form and individually removed and then readded the offending accents, and it's fine now. What a pain! I bet this is a known bug or maybe a feature, but getting the eventos en español in is pretty important to me, so I'll work around as needed.

**Comment by jhelwig** [comment]
So, I have a feeling that this is because of MySQL's atrocious UTF-8 handling. I've been planning on fixing the UTF-8 support (probably by making sure we're using `utf8mb4` everywhere https://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5#21684), but I haven't had a stretch of time where I've also had the energy to do it.

**Comment by ghost** [comment]
I can work around it - and I don't know if others are trying to import accented characters in - if others are, then it's probably worth working on when you get a chunk of time. But I'm pretty motivated to get these in, so I'm happy to do a little massaging to make it work. And thank you for all you do. Really!
